- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variable
      include_vars: vars/bastion_setup

    - name: Import VPC setup variable
      include_vars: vars/output_vars

    - name: example ec2 key
      ec2_key:
        name: yuvki_2023
        region: "{{region}}"
      register: key_out


    - name: store login key
      copy:
       content: "{{key_out.key.private_key}}"
       dest: "./yuvki_2023.pem"
       mode: 0600
      when: key_out.changed

    - name: create security group for baiston host
      ec2_group:
         name: Bastion-host-sg
         description: Allow port 22 from everywhere and all
         region: "{{region}}"
         vpc_id: "{{vpcid}}"
         rules:
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: "{{MYIP}}"
      register: BastionSG_out

    - name: Creating Bastion Host
      ec2:
        key_name: yuvk_2023
        region: "{{region}}"



