---
- name: setup Yuviapp stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC variable
      include_vars: vars/output_vars

    - name: Import yuvi setup variable
      include_vars: vars/yuvistackvars

    - name: create yuvi ec2 key
      ec2_key:
       name: yuvistack_2023
       region: "{{region}}"
      register: yuvistack_2023_out

    - name: store login key
      copy:
        content: "{{yuvistack_2023_out.key.private_key}}"
        dest: "./yuvistack_2023.pem"
        mode: 0600
      when: yuvistack_2023_out.changed

    - name: Create security group for LoadBalancer
      ec2_group:
         name: yuviELB-sg
         description: Allow port 80 from everywhere and allow port within sg
         region: "{{region}}"
         vpc_id: "{{vpcid}}"
         rules:
           - proto: tcp
             from_port: 80
             to_port: 80
             cidr_ip: 0.0.0.0/0
      register: yuviELBsg_out

    - name: Create security group for yuviapp stack
      ec2_group:
          name: yuviStack-sg
          description: Allow port 22 from everywhere and allow port within sg
          region: "{{region}}"
          vpc_id: "{{vpcid}}"
          purge_rules: no
          rules:
                 - proto: tcp
                   from_port: 80
                   to_port: 80
                   group_id: "{{yuviELBsg_out.group_id}}"

                 - proto: tcp
                   from_port: 22
                   to_port: 22
                   group_id: "{{BastionSGid}}"
      register: yuviStackSG_out

    - name: update security group with its own sg id
      ec2_group:
          name: yuviStack-sg
          description: allow port 22 from everywhere and all port within sg
          region: "{{region}}"
          vpc_id: "{{vpcid}}"
          purge_rules: no
          rules:
           - proto: all
             group_id: "{{yuviStackSG_out.group_id}}"

    - name: Creating nginx instance
      ec2_instance:
         name: "Web01-Nginx"
         key_name: yuvki_2023
         region: "{{region}}"
         vpc_subnet_id: "{{privsub1id}}"
         instance_type: t2.micro
         security_group: yuviStack-sg
         image_id: "{{nginx_ami}}"
         wait: yes
         wait_timeout: 300
         tags:
           Name: "Web01-Nginx"
           Project: Yuviapp
           Owner: DevOps Team
      register: web01_out

    - name: Creating Tomcat instance
      ec2_instance:
          name: "App01-Tomcat"
          key_name: yuvki_2023
          region: "{{region}}"
          vpc_subnet_id: "{{privsub1id}}"
          instance_type: t2.micro
          security_group: yuviStack-sg
          image_id: "{{tomcat_ami}}"
          wait: yes
          wait_timeout: 300
          tags:
            Name: "App01-Nginx"
            Project: Yuviapp
            Owner: DevOps Team
      register: app01_out

    - name: Creating Memcache instance
      ec2_instance:
          name: "Mc01-Memcache"
          key_name: yuvki_2023
          region: "{{region}}"
          vpc_subnet_id: "{{privsub1id}}"
          instance_type: t2.micro
          security_group: yuviStack-sg
          image_id: "{{memcache_ami}}"
          wait: yes
          wait_timeout: 300
          tags:
            Name: "Mc01-Memcache"
            Project: Yuviapp
            Owner: DevOps Team
      register: Mem01_out



    - name: Creating RabbitMQ instance
      ec2_instance:
          name: "RMQ01-RabbitMQ"
          key_name: yuvki_2023
          region: "{{region}}"
          vpc_subnet_id: "{{privsub1id}}"
          instance_type: t2.micro
          security_group: yuviStack-sg
          image_id: "{{rmq_ami}}"
          wait: yes
          wait_timeout: 300
          tags:
            Name: "RMQ01-RabbitMQ"
            Project: Yuviapp
            Owner: DevOps Team
      register: rmq01_out



    - name: Creating Mysql instance
      ec2_instance:
          name: "Mysql"
          key_name: yuvki_2023
          region: "{{region}}"
          vpc_subnet_id: "{{privsub1id}}"
          instance_type: t2.micro
          security_group: yuviStack-sg
          image_id: "{{mysql_ami}}"
          wait: yes
          wait_timeout: 300
          tags:
            Name: "Mysql"
            Project: Yuviapp
            Owner: DevOps Team
      register: mysql_out

    - debug:
       var: mysql_out


